### ISSUE TITLE
debugger starts at internal runtime code but not my function 

### ISSUE THREAD

**Issue by dalarworld** [stackery/sss-local-debugging#1]
I have setup stackery & AWS account. I am trying to debug my application. Debugging is starting but stops at following location ...

`stackery local start-api --stack-name serverless-1 --env-name test --aws-profile default --debug-port 5656`

![image](https://user-images.githubusercontent.com/16445005/85205952-44afc100-b33c-11ea-80f6-48f28dba594c.png)
How ever it does not stop in my own function ( using hellow world function from your repo)
![image](https://user-images.githubusercontent.com/16445005/85205986-82ace500-b33c-11ea-9007-6361f162247a.png)
What I have to do to stop it at my function and not internal runtime code

**Comment by dalarworld** [comment]
I have found solution, you should update your documentation  with following information. By adding path sar/{{FunctionName}} it worked. 

`"localRoot": "${workspaceRoot}/{directory of node app}",`

 In my case it was like following...

`"localRoot": "${workspaceRoot}/src/getWelcomePage",`

**Comment by txase** [comment]
Hi @dalarworld! Thanks for opening this issue. Do you have a suggestion for how we can improve the modules in this repo to address your concerns?

Thanks!

**Comment by dalarworld** [comment]
Including launch.json file will be better for people to head start.

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
           
                "name": "Attach to SAM CLI",
                "type": "node",
                "request": "attach",
                "address": "localhost",
                "port": 5656, // set the port to whatever you would like, but it has to match the port in the --debug-port flag
                "localRoot": "${workspaceRoot}/src/getWelcomePage",
                "remoteRoot": "/var/task",
                "protocol": "inspector"
               
            
        }
    ]
}`
